layout_spectrum: 0.11104665106835564
typography_spectrum: 0.7696153085936083
color:
  brandStrength: 0.9674646645986318
  lightness: 0.4620527696389115
  saturation: 0.1286181314989445
  rhythmicContrast: 0.7434344428896645
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
github: true
author:
  name: Dan McClintock
  email: dmcclint@coloradomesa.edu
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39f215fb-0fb2-417c-a30a-d31e24fcd68f.png
name: VR Insights
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e5c1e52-c812-454d-9bc8-58fe0f9869e6.png
title: VR Production Insights
content: []
description: Immersive Video/Graphic/Animation Production Techniques
purpose:
  - type: contact
    url: 'tel:970-255-2649'
    label: Call 970-255-2649
  - type: contact
    url: 'mailto:dmcclint@coloradomesa.edu'
    label: Contact us
