typography_spectrum: 0.6171679
color:
  saturation: 0.2017379844736419
  brandStrength: 1
  lightness: 0.727239331459018
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  rhythmicContrast: 0.7075699296355763
github: true
layout_spectrum: 1
author:
  name: Dan McClintock
  email: dmcclint@coloradomesa.edu
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39f215fb-0fb2-417c-a30a-d31e24fcd68f.png
name: Immersive Design Technology
navigation:
  - name: About Us
    id: f8df6492-384c-49d6-b5e2-34ed69b4ad77
    type: content
  - name: Blog/News
    id: 8c48b0d9-ef12-4047-b50d-46834f5e8eaa
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e5c1e52-c812-454d-9bc8-58fe0f9869e6.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: VR Production Insights
content: []
description: Immersive Video/Graphic/Animation Production Techniques
purpose:
  - type: contact
    url: 'tel:970-255-2649'
    label: Call 970-255-2649
  - type: contact
    url: 'mailto:dmcclint@coloradomesa.edu'
    label: Contact us
