layout_spectrum: 0.5561182947529684
typography_spectrum: 0.5272849330487708
color:
  brandStrength: 0.9667620896388509
  lightness: 0.17723733023583596
  saturation: 0.19527225521457667
  rhythmicContrast: 0.7760498221468476
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
github: true
author:
  name: Dan McClintock
  email: dmcclint@coloradomesa.edu
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39f215fb-0fb2-417c-a30a-d31e24fcd68f.png
name: VR Insights
navigation:
  - name: Blog/News
    id: 8c48b0d9-ef12-4047-b50d-46834f5e8eaa
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e5c1e52-c812-454d-9bc8-58fe0f9869e6.png
title: VR Production Insights
content: []
description: Immersive Video/Graphic/Animation Production Techniques
purpose:
  - type: contact
    url: 'tel:970-255-2649'
    label: Call 970-255-2649
  - type: contact
    url: 'mailto:dmcclint@coloradomesa.edu'
    label: Contact us
